// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_sobel_axi_stream_top_hls_sobel_axi_stream_top,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.268000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=3,HLS_SYN_DSP=0,HLS_SYN_FF=3258,HLS_SYN_LUT=4257,HLS_VERSION=2022_2}" *)

module hls_sobel_axi_stream_top (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        p_src_TDATA,
        p_src_TKEEP,
        p_src_TSTRB,
        p_src_TUSER,
        p_src_TLAST,
        p_src_TID,
        p_src_TDEST,
        p_dst_TDATA,
        p_dst_TKEEP,
        p_dst_TSTRB,
        p_dst_TUSER,
        p_dst_TLAST,
        p_dst_TID,
        p_dst_TDEST,
        p_src_TVALID,
        p_src_TREADY,
        p_dst_TVALID,
        p_dst_TREADY
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [31:0] p_src_TDATA;
input  [3:0] p_src_TKEEP;
input  [3:0] p_src_TSTRB;
input  [0:0] p_src_TUSER;
input  [0:0] p_src_TLAST;
input  [0:0] p_src_TID;
input  [0:0] p_src_TDEST;
output  [31:0] p_dst_TDATA;
output  [3:0] p_dst_TKEEP;
output  [3:0] p_dst_TSTRB;
output  [0:0] p_dst_TUSER;
output  [0:0] p_dst_TLAST;
output  [0:0] p_dst_TID;
output  [0:0] p_dst_TDEST;
input   p_src_TVALID;
output   p_src_TREADY;
output   p_dst_TVALID;
input   p_dst_TREADY;

 reg    ap_rst_n_inv;
wire   [31:0] rows;
wire   [31:0] cols;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    Block_entry1_proc_U0_ap_start;
wire    Block_entry1_proc_U0_ap_done;
wire    Block_entry1_proc_U0_ap_continue;
wire    Block_entry1_proc_U0_ap_idle;
wire    Block_entry1_proc_U0_ap_ready;
wire   [31:0] Block_entry1_proc_U0_ap_return_0;
wire   [31:0] Block_entry1_proc_U0_ap_return_1;
wire   [31:0] Block_entry1_proc_U0_ap_return_2;
wire   [31:0] Block_entry1_proc_U0_ap_return_3;
wire   [31:0] Block_entry1_proc_U0_ap_return_4;
wire   [31:0] Block_entry1_proc_U0_ap_return_5;
wire   [31:0] Block_entry1_proc_U0_ap_return_6;
wire   [31:0] Block_entry1_proc_U0_ap_return_7;
wire   [31:0] Block_entry1_proc_U0_ap_return_8;
wire   [31:0] Block_entry1_proc_U0_ap_return_9;
wire    ap_channel_done_img_buf_0_cols_c16_channel;
wire    img_buf_0_cols_c16_channel_full_n;
reg    ap_sync_reg_channel_write_img_buf_0_cols_c16_channel;
wire    ap_sync_channel_write_img_buf_0_cols_c16_channel;
wire    ap_channel_done_img_buf_0_rows_c15_channel;
wire    img_buf_0_rows_c15_channel_full_n;
reg    ap_sync_reg_channel_write_img_buf_0_rows_c15_channel;
wire    ap_sync_channel_write_img_buf_0_rows_c15_channel;
wire    ap_channel_done_img_buf_3_cols_channel;
wire    img_buf_3_cols_channel_full_n;
reg    ap_sync_reg_channel_write_img_buf_3_cols_channel;
wire    ap_sync_channel_write_img_buf_3_cols_channel;
wire    ap_channel_done_img_buf_3_rows_channel;
wire    img_buf_3_rows_channel_full_n;
reg    ap_sync_reg_channel_write_img_buf_3_rows_channel;
wire    ap_sync_channel_write_img_buf_3_rows_channel;
wire    ap_channel_done_img_buf_2_cols_channel;
wire    img_buf_2_cols_channel_full_n;
reg    ap_sync_reg_channel_write_img_buf_2_cols_channel;
wire    ap_sync_channel_write_img_buf_2_cols_channel;
wire    ap_channel_done_img_buf_2_rows_channel;
wire    img_buf_2_rows_channel_full_n;
reg    ap_sync_reg_channel_write_img_buf_2_rows_channel;
wire    ap_sync_channel_write_img_buf_2_rows_channel;
wire    ap_channel_done_img_buf_1a_cols_channel;
wire    img_buf_1a_cols_channel_full_n;
reg    ap_sync_reg_channel_write_img_buf_1a_cols_channel;
wire    ap_sync_channel_write_img_buf_1a_cols_channel;
wire    ap_channel_done_img_buf_1a_rows_channel;
wire    img_buf_1a_rows_channel_full_n;
reg    ap_sync_reg_channel_write_img_buf_1a_rows_channel;
wire    ap_sync_channel_write_img_buf_1a_rows_channel;
wire    ap_channel_done_img_buf_1_cols_channel;
wire    img_buf_1_cols_channel_full_n;
reg    ap_sync_reg_channel_write_img_buf_1_cols_channel;
wire    ap_sync_channel_write_img_buf_1_cols_channel;
wire    ap_channel_done_img_buf_1_rows_channel;
wire    img_buf_1_rows_channel_full_n;
reg    ap_sync_reg_channel_write_img_buf_1_rows_channel;
wire    ap_sync_channel_write_img_buf_1_rows_channel;
wire    AXIvideo2xfMat_32_9_128_128_1_2_U0_ap_start;
wire    AXIvideo2xfMat_32_9_128_128_1_2_U0_ap_done;
wire    AXIvideo2xfMat_32_9_128_128_1_2_U0_ap_continue;
wire    AXIvideo2xfMat_32_9_128_128_1_2_U0_ap_idle;
wire    AXIvideo2xfMat_32_9_128_128_1_2_U0_ap_ready;
wire    AXIvideo2xfMat_32_9_128_128_1_2_U0_start_out;
wire    AXIvideo2xfMat_32_9_128_128_1_2_U0_start_write;
wire    AXIvideo2xfMat_32_9_128_128_1_2_U0_p_src_TREADY;
wire   [23:0] AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_data103_din;
wire    AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_data103_write;
wire   [31:0] AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_rows_c_din;
wire    AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_rows_c_write;
wire   [31:0] AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_cols_c_din;
wire    AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_cols_c_write;
wire    bgr2gray_9_0_128_128_1_2_2_U0_ap_start;
wire    bgr2gray_9_0_128_128_1_2_2_U0_ap_done;
wire    bgr2gray_9_0_128_128_1_2_2_U0_ap_continue;
wire    bgr2gray_9_0_128_128_1_2_2_U0_ap_idle;
wire    bgr2gray_9_0_128_128_1_2_2_U0_ap_ready;
wire    bgr2gray_9_0_128_128_1_2_2_U0_p_src_rows_read;
wire    bgr2gray_9_0_128_128_1_2_2_U0_p_src_cols_read;
wire    bgr2gray_9_0_128_128_1_2_2_U0_img_buf_0_data103_read;
wire   [7:0] bgr2gray_9_0_128_128_1_2_2_U0_img_buf_1_data104_din;
wire    bgr2gray_9_0_128_128_1_2_2_U0_img_buf_1_data104_write;
wire    Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_ap_start;
wire    Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_ap_done;
wire    Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_ap_continue;
wire    Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_ap_idle;
wire    Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_ap_ready;
wire    Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_img_buf_1_data104_read;
wire   [7:0] Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_img_buf_1a_data105_din;
wire    Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_img_buf_1a_data105_write;
wire   [7:0] Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_img_buf_1b_data106_din;
wire    Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_img_buf_1b_data106_write;
wire    addWeighted_0_0_128_128_1_2_2_2_U0_ap_start;
wire    addWeighted_0_0_128_128_1_2_2_2_U0_ap_done;
wire    addWeighted_0_0_128_128_1_2_2_2_U0_ap_continue;
wire    addWeighted_0_0_128_128_1_2_2_2_U0_ap_idle;
wire    addWeighted_0_0_128_128_1_2_2_2_U0_ap_ready;
wire    addWeighted_0_0_128_128_1_2_2_2_U0_img_buf_1a_data105_read;
wire    addWeighted_0_0_128_128_1_2_2_2_U0_img_buf_1b_data106_read;
wire   [7:0] addWeighted_0_0_128_128_1_2_2_2_U0_img_buf_2_data107_din;
wire    addWeighted_0_0_128_128_1_2_2_2_U0_img_buf_2_data107_write;
wire    gray2bgr_0_9_128_128_1_2_2_U0_ap_start;
wire    gray2bgr_0_9_128_128_1_2_2_U0_ap_done;
wire    gray2bgr_0_9_128_128_1_2_2_U0_ap_continue;
wire    gray2bgr_0_9_128_128_1_2_2_U0_ap_idle;
wire    gray2bgr_0_9_128_128_1_2_2_U0_ap_ready;
wire    gray2bgr_0_9_128_128_1_2_2_U0_img_buf_2_data107_read;
wire   [23:0] gray2bgr_0_9_128_128_1_2_2_U0_img_buf_3_data108_din;
wire    gray2bgr_0_9_128_128_1_2_2_U0_img_buf_3_data108_write;
wire    xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_start;
wire    xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_done;
wire    xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_continue;
wire    xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_idle;
wire    xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_ready;
wire    xfMat2AXIvideo_32_9_128_128_1_2_U0_img_buf_3_data108_read;
wire   [31:0] xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TDATA;
wire    xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TVALID;
wire   [3:0] xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TKEEP;
wire   [3:0] xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TSTRB;
wire   [0:0] xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TUSER;
wire   [0:0] xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TLAST;
wire   [0:0] xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TID;
wire   [0:0] xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TDEST;
wire   [31:0] img_buf_1_rows_channel_dout;
wire   [2:0] img_buf_1_rows_channel_num_data_valid;
wire   [2:0] img_buf_1_rows_channel_fifo_cap;
wire    img_buf_1_rows_channel_empty_n;
wire   [31:0] img_buf_1_cols_channel_dout;
wire   [2:0] img_buf_1_cols_channel_num_data_valid;
wire   [2:0] img_buf_1_cols_channel_fifo_cap;
wire    img_buf_1_cols_channel_empty_n;
wire   [31:0] img_buf_1a_rows_channel_dout;
wire   [3:0] img_buf_1a_rows_channel_num_data_valid;
wire   [3:0] img_buf_1a_rows_channel_fifo_cap;
wire    img_buf_1a_rows_channel_empty_n;
wire   [31:0] img_buf_1a_cols_channel_dout;
wire   [3:0] img_buf_1a_cols_channel_num_data_valid;
wire   [3:0] img_buf_1a_cols_channel_fifo_cap;
wire    img_buf_1a_cols_channel_empty_n;
wire   [31:0] img_buf_2_rows_channel_dout;
wire   [3:0] img_buf_2_rows_channel_num_data_valid;
wire   [3:0] img_buf_2_rows_channel_fifo_cap;
wire    img_buf_2_rows_channel_empty_n;
wire   [31:0] img_buf_2_cols_channel_dout;
wire   [3:0] img_buf_2_cols_channel_num_data_valid;
wire   [3:0] img_buf_2_cols_channel_fifo_cap;
wire    img_buf_2_cols_channel_empty_n;
wire   [31:0] img_buf_3_rows_channel_dout;
wire   [3:0] img_buf_3_rows_channel_num_data_valid;
wire   [3:0] img_buf_3_rows_channel_fifo_cap;
wire    img_buf_3_rows_channel_empty_n;
wire   [31:0] img_buf_3_cols_channel_dout;
wire   [3:0] img_buf_3_cols_channel_num_data_valid;
wire   [3:0] img_buf_3_cols_channel_fifo_cap;
wire    img_buf_3_cols_channel_empty_n;
wire   [31:0] img_buf_0_rows_c15_channel_dout;
wire   [1:0] img_buf_0_rows_c15_channel_num_data_valid;
wire   [1:0] img_buf_0_rows_c15_channel_fifo_cap;
wire    img_buf_0_rows_c15_channel_empty_n;
wire   [31:0] img_buf_0_cols_c16_channel_dout;
wire   [1:0] img_buf_0_cols_c16_channel_num_data_valid;
wire   [1:0] img_buf_0_cols_c16_channel_fifo_cap;
wire    img_buf_0_cols_c16_channel_empty_n;
wire    img_buf_0_data_full_n;
wire   [23:0] img_buf_0_data_dout;
wire   [1:0] img_buf_0_data_num_data_valid;
wire   [1:0] img_buf_0_data_fifo_cap;
wire    img_buf_0_data_empty_n;
wire    img_buf_0_rows_c_full_n;
wire   [31:0] img_buf_0_rows_c_dout;
wire   [1:0] img_buf_0_rows_c_num_data_valid;
wire   [1:0] img_buf_0_rows_c_fifo_cap;
wire    img_buf_0_rows_c_empty_n;
wire    img_buf_0_cols_c_full_n;
wire   [31:0] img_buf_0_cols_c_dout;
wire   [1:0] img_buf_0_cols_c_num_data_valid;
wire   [1:0] img_buf_0_cols_c_fifo_cap;
wire    img_buf_0_cols_c_empty_n;
wire    img_buf_1_data_full_n;
wire   [7:0] img_buf_1_data_dout;
wire   [1:0] img_buf_1_data_num_data_valid;
wire   [1:0] img_buf_1_data_fifo_cap;
wire    img_buf_1_data_empty_n;
wire    img_buf_1a_data_full_n;
wire   [7:0] img_buf_1a_data_dout;
wire   [1:0] img_buf_1a_data_num_data_valid;
wire   [1:0] img_buf_1a_data_fifo_cap;
wire    img_buf_1a_data_empty_n;
wire    img_buf_1b_data_full_n;
wire   [7:0] img_buf_1b_data_dout;
wire   [1:0] img_buf_1b_data_num_data_valid;
wire   [1:0] img_buf_1b_data_fifo_cap;
wire    img_buf_1b_data_empty_n;
wire    img_buf_2_data_full_n;
wire   [7:0] img_buf_2_data_dout;
wire   [1:0] img_buf_2_data_num_data_valid;
wire   [1:0] img_buf_2_data_fifo_cap;
wire    img_buf_2_data_empty_n;
wire    img_buf_3_data_full_n;
wire   [23:0] img_buf_3_data_dout;
wire   [1:0] img_buf_3_data_num_data_valid;
wire   [1:0] img_buf_3_data_fifo_cap;
wire    img_buf_3_data_empty_n;
wire   [0:0] start_for_bgr2gray_9_0_128_128_1_2_2_U0_din;
wire    start_for_bgr2gray_9_0_128_128_1_2_2_U0_full_n;
wire   [0:0] start_for_bgr2gray_9_0_128_128_1_2_2_U0_dout;
wire    start_for_bgr2gray_9_0_128_128_1_2_2_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_img_buf_0_cols_c16_channel = 1'b0;
#0 ap_sync_reg_channel_write_img_buf_0_rows_c15_channel = 1'b0;
#0 ap_sync_reg_channel_write_img_buf_3_cols_channel = 1'b0;
#0 ap_sync_reg_channel_write_img_buf_3_rows_channel = 1'b0;
#0 ap_sync_reg_channel_write_img_buf_2_cols_channel = 1'b0;
#0 ap_sync_reg_channel_write_img_buf_2_rows_channel = 1'b0;
#0 ap_sync_reg_channel_write_img_buf_1a_cols_channel = 1'b0;
#0 ap_sync_reg_channel_write_img_buf_1a_rows_channel = 1'b0;
#0 ap_sync_reg_channel_write_img_buf_1_cols_channel = 1'b0;
#0 ap_sync_reg_channel_write_img_buf_1_rows_channel = 1'b0;
end

hls_sobel_axi_stream_top_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .rows(rows),
    .cols(cols),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

hls_sobel_axi_stream_top_Block_entry1_proc Block_entry1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry1_proc_U0_ap_start),
    .ap_done(Block_entry1_proc_U0_ap_done),
    .ap_continue(Block_entry1_proc_U0_ap_continue),
    .ap_idle(Block_entry1_proc_U0_ap_idle),
    .ap_ready(Block_entry1_proc_U0_ap_ready),
    .rows(rows),
    .cols(cols),
    .ap_return_0(Block_entry1_proc_U0_ap_return_0),
    .ap_return_1(Block_entry1_proc_U0_ap_return_1),
    .ap_return_2(Block_entry1_proc_U0_ap_return_2),
    .ap_return_3(Block_entry1_proc_U0_ap_return_3),
    .ap_return_4(Block_entry1_proc_U0_ap_return_4),
    .ap_return_5(Block_entry1_proc_U0_ap_return_5),
    .ap_return_6(Block_entry1_proc_U0_ap_return_6),
    .ap_return_7(Block_entry1_proc_U0_ap_return_7),
    .ap_return_8(Block_entry1_proc_U0_ap_return_8),
    .ap_return_9(Block_entry1_proc_U0_ap_return_9)
);

hls_sobel_axi_stream_top_AXIvideo2xfMat_32_9_128_128_1_2_s AXIvideo2xfMat_32_9_128_128_1_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2xfMat_32_9_128_128_1_2_U0_ap_start),
    .start_full_n(start_for_bgr2gray_9_0_128_128_1_2_2_U0_full_n),
    .ap_done(AXIvideo2xfMat_32_9_128_128_1_2_U0_ap_done),
    .ap_continue(AXIvideo2xfMat_32_9_128_128_1_2_U0_ap_continue),
    .ap_idle(AXIvideo2xfMat_32_9_128_128_1_2_U0_ap_idle),
    .ap_ready(AXIvideo2xfMat_32_9_128_128_1_2_U0_ap_ready),
    .start_out(AXIvideo2xfMat_32_9_128_128_1_2_U0_start_out),
    .start_write(AXIvideo2xfMat_32_9_128_128_1_2_U0_start_write),
    .p_src_TDATA(p_src_TDATA),
    .p_src_TVALID(p_src_TVALID),
    .p_src_TREADY(AXIvideo2xfMat_32_9_128_128_1_2_U0_p_src_TREADY),
    .p_src_TKEEP(p_src_TKEEP),
    .p_src_TSTRB(p_src_TSTRB),
    .p_src_TUSER(p_src_TUSER),
    .p_src_TLAST(p_src_TLAST),
    .p_src_TID(p_src_TID),
    .p_src_TDEST(p_src_TDEST),
    .p_read(img_buf_0_rows_c15_channel_dout),
    .p_read1(img_buf_0_cols_c16_channel_dout),
    .img_buf_0_data103_din(AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_data103_din),
    .img_buf_0_data103_num_data_valid(img_buf_0_data_num_data_valid),
    .img_buf_0_data103_fifo_cap(img_buf_0_data_fifo_cap),
    .img_buf_0_data103_full_n(img_buf_0_data_full_n),
    .img_buf_0_data103_write(AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_data103_write),
    .img_buf_0_rows_c_din(AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_rows_c_din),
    .img_buf_0_rows_c_num_data_valid(img_buf_0_rows_c_num_data_valid),
    .img_buf_0_rows_c_fifo_cap(img_buf_0_rows_c_fifo_cap),
    .img_buf_0_rows_c_full_n(img_buf_0_rows_c_full_n),
    .img_buf_0_rows_c_write(AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_rows_c_write),
    .img_buf_0_cols_c_din(AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_cols_c_din),
    .img_buf_0_cols_c_num_data_valid(img_buf_0_cols_c_num_data_valid),
    .img_buf_0_cols_c_fifo_cap(img_buf_0_cols_c_fifo_cap),
    .img_buf_0_cols_c_full_n(img_buf_0_cols_c_full_n),
    .img_buf_0_cols_c_write(AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_cols_c_write)
);

hls_sobel_axi_stream_top_bgr2gray_9_0_128_128_1_2_2_s bgr2gray_9_0_128_128_1_2_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(bgr2gray_9_0_128_128_1_2_2_U0_ap_start),
    .ap_done(bgr2gray_9_0_128_128_1_2_2_U0_ap_done),
    .ap_continue(bgr2gray_9_0_128_128_1_2_2_U0_ap_continue),
    .ap_idle(bgr2gray_9_0_128_128_1_2_2_U0_ap_idle),
    .ap_ready(bgr2gray_9_0_128_128_1_2_2_U0_ap_ready),
    .p_src_rows_dout(img_buf_0_rows_c_dout),
    .p_src_rows_num_data_valid(img_buf_0_rows_c_num_data_valid),
    .p_src_rows_fifo_cap(img_buf_0_rows_c_fifo_cap),
    .p_src_rows_empty_n(img_buf_0_rows_c_empty_n),
    .p_src_rows_read(bgr2gray_9_0_128_128_1_2_2_U0_p_src_rows_read),
    .p_src_cols_dout(img_buf_0_cols_c_dout),
    .p_src_cols_num_data_valid(img_buf_0_cols_c_num_data_valid),
    .p_src_cols_fifo_cap(img_buf_0_cols_c_fifo_cap),
    .p_src_cols_empty_n(img_buf_0_cols_c_empty_n),
    .p_src_cols_read(bgr2gray_9_0_128_128_1_2_2_U0_p_src_cols_read),
    .img_buf_0_data103_dout(img_buf_0_data_dout),
    .img_buf_0_data103_num_data_valid(img_buf_0_data_num_data_valid),
    .img_buf_0_data103_fifo_cap(img_buf_0_data_fifo_cap),
    .img_buf_0_data103_empty_n(img_buf_0_data_empty_n),
    .img_buf_0_data103_read(bgr2gray_9_0_128_128_1_2_2_U0_img_buf_0_data103_read),
    .img_buf_1_data104_din(bgr2gray_9_0_128_128_1_2_2_U0_img_buf_1_data104_din),
    .img_buf_1_data104_num_data_valid(img_buf_1_data_num_data_valid),
    .img_buf_1_data104_fifo_cap(img_buf_1_data_fifo_cap),
    .img_buf_1_data104_full_n(img_buf_1_data_full_n),
    .img_buf_1_data104_write(bgr2gray_9_0_128_128_1_2_2_U0_img_buf_1_data104_write)
);

hls_sobel_axi_stream_top_Sobel_0_3_0_0_128_128_1_false_2_2_2_s Sobel_0_3_0_0_128_128_1_false_2_2_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_ap_start),
    .ap_done(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_ap_done),
    .ap_continue(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_ap_continue),
    .ap_idle(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_ap_idle),
    .ap_ready(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_ap_ready),
    .p_read(img_buf_1_rows_channel_dout),
    .p_read1(img_buf_1_cols_channel_dout),
    .img_buf_1_data104_dout(img_buf_1_data_dout),
    .img_buf_1_data104_num_data_valid(img_buf_1_data_num_data_valid),
    .img_buf_1_data104_fifo_cap(img_buf_1_data_fifo_cap),
    .img_buf_1_data104_empty_n(img_buf_1_data_empty_n),
    .img_buf_1_data104_read(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_img_buf_1_data104_read),
    .img_buf_1a_data105_din(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_img_buf_1a_data105_din),
    .img_buf_1a_data105_num_data_valid(img_buf_1a_data_num_data_valid),
    .img_buf_1a_data105_fifo_cap(img_buf_1a_data_fifo_cap),
    .img_buf_1a_data105_full_n(img_buf_1a_data_full_n),
    .img_buf_1a_data105_write(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_img_buf_1a_data105_write),
    .img_buf_1b_data106_din(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_img_buf_1b_data106_din),
    .img_buf_1b_data106_num_data_valid(img_buf_1b_data_num_data_valid),
    .img_buf_1b_data106_fifo_cap(img_buf_1b_data_fifo_cap),
    .img_buf_1b_data106_full_n(img_buf_1b_data_full_n),
    .img_buf_1b_data106_write(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_img_buf_1b_data106_write)
);

hls_sobel_axi_stream_top_addWeighted_0_0_128_128_1_2_2_2_s addWeighted_0_0_128_128_1_2_2_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(addWeighted_0_0_128_128_1_2_2_2_U0_ap_start),
    .ap_done(addWeighted_0_0_128_128_1_2_2_2_U0_ap_done),
    .ap_continue(addWeighted_0_0_128_128_1_2_2_2_U0_ap_continue),
    .ap_idle(addWeighted_0_0_128_128_1_2_2_2_U0_ap_idle),
    .ap_ready(addWeighted_0_0_128_128_1_2_2_2_U0_ap_ready),
    .p_read(img_buf_1a_rows_channel_dout),
    .p_read1(img_buf_1a_cols_channel_dout),
    .img_buf_1a_data105_dout(img_buf_1a_data_dout),
    .img_buf_1a_data105_num_data_valid(img_buf_1a_data_num_data_valid),
    .img_buf_1a_data105_fifo_cap(img_buf_1a_data_fifo_cap),
    .img_buf_1a_data105_empty_n(img_buf_1a_data_empty_n),
    .img_buf_1a_data105_read(addWeighted_0_0_128_128_1_2_2_2_U0_img_buf_1a_data105_read),
    .img_buf_1b_data106_dout(img_buf_1b_data_dout),
    .img_buf_1b_data106_num_data_valid(img_buf_1b_data_num_data_valid),
    .img_buf_1b_data106_fifo_cap(img_buf_1b_data_fifo_cap),
    .img_buf_1b_data106_empty_n(img_buf_1b_data_empty_n),
    .img_buf_1b_data106_read(addWeighted_0_0_128_128_1_2_2_2_U0_img_buf_1b_data106_read),
    .img_buf_2_data107_din(addWeighted_0_0_128_128_1_2_2_2_U0_img_buf_2_data107_din),
    .img_buf_2_data107_num_data_valid(img_buf_2_data_num_data_valid),
    .img_buf_2_data107_fifo_cap(img_buf_2_data_fifo_cap),
    .img_buf_2_data107_full_n(img_buf_2_data_full_n),
    .img_buf_2_data107_write(addWeighted_0_0_128_128_1_2_2_2_U0_img_buf_2_data107_write)
);

hls_sobel_axi_stream_top_gray2bgr_0_9_128_128_1_2_2_s gray2bgr_0_9_128_128_1_2_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(gray2bgr_0_9_128_128_1_2_2_U0_ap_start),
    .ap_done(gray2bgr_0_9_128_128_1_2_2_U0_ap_done),
    .ap_continue(gray2bgr_0_9_128_128_1_2_2_U0_ap_continue),
    .ap_idle(gray2bgr_0_9_128_128_1_2_2_U0_ap_idle),
    .ap_ready(gray2bgr_0_9_128_128_1_2_2_U0_ap_ready),
    .p_read(img_buf_2_rows_channel_dout),
    .p_read1(img_buf_2_cols_channel_dout),
    .img_buf_2_data107_dout(img_buf_2_data_dout),
    .img_buf_2_data107_num_data_valid(img_buf_2_data_num_data_valid),
    .img_buf_2_data107_fifo_cap(img_buf_2_data_fifo_cap),
    .img_buf_2_data107_empty_n(img_buf_2_data_empty_n),
    .img_buf_2_data107_read(gray2bgr_0_9_128_128_1_2_2_U0_img_buf_2_data107_read),
    .img_buf_3_data108_din(gray2bgr_0_9_128_128_1_2_2_U0_img_buf_3_data108_din),
    .img_buf_3_data108_num_data_valid(img_buf_3_data_num_data_valid),
    .img_buf_3_data108_fifo_cap(img_buf_3_data_fifo_cap),
    .img_buf_3_data108_full_n(img_buf_3_data_full_n),
    .img_buf_3_data108_write(gray2bgr_0_9_128_128_1_2_2_U0_img_buf_3_data108_write)
);

hls_sobel_axi_stream_top_xfMat2AXIvideo_32_9_128_128_1_2_s xfMat2AXIvideo_32_9_128_128_1_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_start),
    .ap_done(xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_done),
    .ap_continue(xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_continue),
    .ap_idle(xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_idle),
    .ap_ready(xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_ready),
    .p_read(img_buf_3_rows_channel_dout),
    .p_read1(img_buf_3_cols_channel_dout),
    .img_buf_3_data108_dout(img_buf_3_data_dout),
    .img_buf_3_data108_num_data_valid(img_buf_3_data_num_data_valid),
    .img_buf_3_data108_fifo_cap(img_buf_3_data_fifo_cap),
    .img_buf_3_data108_empty_n(img_buf_3_data_empty_n),
    .img_buf_3_data108_read(xfMat2AXIvideo_32_9_128_128_1_2_U0_img_buf_3_data108_read),
    .p_dst_TDATA(xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TDATA),
    .p_dst_TVALID(xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TVALID),
    .p_dst_TREADY(p_dst_TREADY),
    .p_dst_TKEEP(xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TKEEP),
    .p_dst_TSTRB(xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TSTRB),
    .p_dst_TUSER(xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TUSER),
    .p_dst_TLAST(xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TLAST),
    .p_dst_TID(xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TID),
    .p_dst_TDEST(xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TDEST)
);

hls_sobel_axi_stream_top_fifo_w32_d4_S img_buf_1_rows_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_0),
    .if_full_n(img_buf_1_rows_channel_full_n),
    .if_write(ap_channel_done_img_buf_1_rows_channel),
    .if_dout(img_buf_1_rows_channel_dout),
    .if_num_data_valid(img_buf_1_rows_channel_num_data_valid),
    .if_fifo_cap(img_buf_1_rows_channel_fifo_cap),
    .if_empty_n(img_buf_1_rows_channel_empty_n),
    .if_read(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_ap_ready)
);

hls_sobel_axi_stream_top_fifo_w32_d4_S img_buf_1_cols_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_1),
    .if_full_n(img_buf_1_cols_channel_full_n),
    .if_write(ap_channel_done_img_buf_1_cols_channel),
    .if_dout(img_buf_1_cols_channel_dout),
    .if_num_data_valid(img_buf_1_cols_channel_num_data_valid),
    .if_fifo_cap(img_buf_1_cols_channel_fifo_cap),
    .if_empty_n(img_buf_1_cols_channel_empty_n),
    .if_read(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_ap_ready)
);

hls_sobel_axi_stream_top_fifo_w32_d5_S img_buf_1a_rows_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_2),
    .if_full_n(img_buf_1a_rows_channel_full_n),
    .if_write(ap_channel_done_img_buf_1a_rows_channel),
    .if_dout(img_buf_1a_rows_channel_dout),
    .if_num_data_valid(img_buf_1a_rows_channel_num_data_valid),
    .if_fifo_cap(img_buf_1a_rows_channel_fifo_cap),
    .if_empty_n(img_buf_1a_rows_channel_empty_n),
    .if_read(addWeighted_0_0_128_128_1_2_2_2_U0_ap_ready)
);

hls_sobel_axi_stream_top_fifo_w32_d5_S img_buf_1a_cols_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_3),
    .if_full_n(img_buf_1a_cols_channel_full_n),
    .if_write(ap_channel_done_img_buf_1a_cols_channel),
    .if_dout(img_buf_1a_cols_channel_dout),
    .if_num_data_valid(img_buf_1a_cols_channel_num_data_valid),
    .if_fifo_cap(img_buf_1a_cols_channel_fifo_cap),
    .if_empty_n(img_buf_1a_cols_channel_empty_n),
    .if_read(addWeighted_0_0_128_128_1_2_2_2_U0_ap_ready)
);

hls_sobel_axi_stream_top_fifo_w32_d6_S img_buf_2_rows_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_4),
    .if_full_n(img_buf_2_rows_channel_full_n),
    .if_write(ap_channel_done_img_buf_2_rows_channel),
    .if_dout(img_buf_2_rows_channel_dout),
    .if_num_data_valid(img_buf_2_rows_channel_num_data_valid),
    .if_fifo_cap(img_buf_2_rows_channel_fifo_cap),
    .if_empty_n(img_buf_2_rows_channel_empty_n),
    .if_read(gray2bgr_0_9_128_128_1_2_2_U0_ap_ready)
);

hls_sobel_axi_stream_top_fifo_w32_d6_S img_buf_2_cols_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_5),
    .if_full_n(img_buf_2_cols_channel_full_n),
    .if_write(ap_channel_done_img_buf_2_cols_channel),
    .if_dout(img_buf_2_cols_channel_dout),
    .if_num_data_valid(img_buf_2_cols_channel_num_data_valid),
    .if_fifo_cap(img_buf_2_cols_channel_fifo_cap),
    .if_empty_n(img_buf_2_cols_channel_empty_n),
    .if_read(gray2bgr_0_9_128_128_1_2_2_U0_ap_ready)
);

hls_sobel_axi_stream_top_fifo_w32_d7_S img_buf_3_rows_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_6),
    .if_full_n(img_buf_3_rows_channel_full_n),
    .if_write(ap_channel_done_img_buf_3_rows_channel),
    .if_dout(img_buf_3_rows_channel_dout),
    .if_num_data_valid(img_buf_3_rows_channel_num_data_valid),
    .if_fifo_cap(img_buf_3_rows_channel_fifo_cap),
    .if_empty_n(img_buf_3_rows_channel_empty_n),
    .if_read(xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_ready)
);

hls_sobel_axi_stream_top_fifo_w32_d7_S img_buf_3_cols_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_7),
    .if_full_n(img_buf_3_cols_channel_full_n),
    .if_write(ap_channel_done_img_buf_3_cols_channel),
    .if_dout(img_buf_3_cols_channel_dout),
    .if_num_data_valid(img_buf_3_cols_channel_num_data_valid),
    .if_fifo_cap(img_buf_3_cols_channel_fifo_cap),
    .if_empty_n(img_buf_3_cols_channel_empty_n),
    .if_read(xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_ready)
);

hls_sobel_axi_stream_top_fifo_w32_d2_S img_buf_0_rows_c15_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_8),
    .if_full_n(img_buf_0_rows_c15_channel_full_n),
    .if_write(ap_channel_done_img_buf_0_rows_c15_channel),
    .if_dout(img_buf_0_rows_c15_channel_dout),
    .if_num_data_valid(img_buf_0_rows_c15_channel_num_data_valid),
    .if_fifo_cap(img_buf_0_rows_c15_channel_fifo_cap),
    .if_empty_n(img_buf_0_rows_c15_channel_empty_n),
    .if_read(AXIvideo2xfMat_32_9_128_128_1_2_U0_ap_ready)
);

hls_sobel_axi_stream_top_fifo_w32_d2_S img_buf_0_cols_c16_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_9),
    .if_full_n(img_buf_0_cols_c16_channel_full_n),
    .if_write(ap_channel_done_img_buf_0_cols_c16_channel),
    .if_dout(img_buf_0_cols_c16_channel_dout),
    .if_num_data_valid(img_buf_0_cols_c16_channel_num_data_valid),
    .if_fifo_cap(img_buf_0_cols_c16_channel_fifo_cap),
    .if_empty_n(img_buf_0_cols_c16_channel_empty_n),
    .if_read(AXIvideo2xfMat_32_9_128_128_1_2_U0_ap_ready)
);

hls_sobel_axi_stream_top_fifo_w24_d2_S img_buf_0_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_data103_din),
    .if_full_n(img_buf_0_data_full_n),
    .if_write(AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_data103_write),
    .if_dout(img_buf_0_data_dout),
    .if_num_data_valid(img_buf_0_data_num_data_valid),
    .if_fifo_cap(img_buf_0_data_fifo_cap),
    .if_empty_n(img_buf_0_data_empty_n),
    .if_read(bgr2gray_9_0_128_128_1_2_2_U0_img_buf_0_data103_read)
);

hls_sobel_axi_stream_top_fifo_w32_d2_S img_buf_0_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_rows_c_din),
    .if_full_n(img_buf_0_rows_c_full_n),
    .if_write(AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_rows_c_write),
    .if_dout(img_buf_0_rows_c_dout),
    .if_num_data_valid(img_buf_0_rows_c_num_data_valid),
    .if_fifo_cap(img_buf_0_rows_c_fifo_cap),
    .if_empty_n(img_buf_0_rows_c_empty_n),
    .if_read(bgr2gray_9_0_128_128_1_2_2_U0_p_src_rows_read)
);

hls_sobel_axi_stream_top_fifo_w32_d2_S img_buf_0_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_cols_c_din),
    .if_full_n(img_buf_0_cols_c_full_n),
    .if_write(AXIvideo2xfMat_32_9_128_128_1_2_U0_img_buf_0_cols_c_write),
    .if_dout(img_buf_0_cols_c_dout),
    .if_num_data_valid(img_buf_0_cols_c_num_data_valid),
    .if_fifo_cap(img_buf_0_cols_c_fifo_cap),
    .if_empty_n(img_buf_0_cols_c_empty_n),
    .if_read(bgr2gray_9_0_128_128_1_2_2_U0_p_src_cols_read)
);

hls_sobel_axi_stream_top_fifo_w8_d2_S img_buf_1_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(bgr2gray_9_0_128_128_1_2_2_U0_img_buf_1_data104_din),
    .if_full_n(img_buf_1_data_full_n),
    .if_write(bgr2gray_9_0_128_128_1_2_2_U0_img_buf_1_data104_write),
    .if_dout(img_buf_1_data_dout),
    .if_num_data_valid(img_buf_1_data_num_data_valid),
    .if_fifo_cap(img_buf_1_data_fifo_cap),
    .if_empty_n(img_buf_1_data_empty_n),
    .if_read(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_img_buf_1_data104_read)
);

hls_sobel_axi_stream_top_fifo_w8_d2_S img_buf_1a_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_img_buf_1a_data105_din),
    .if_full_n(img_buf_1a_data_full_n),
    .if_write(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_img_buf_1a_data105_write),
    .if_dout(img_buf_1a_data_dout),
    .if_num_data_valid(img_buf_1a_data_num_data_valid),
    .if_fifo_cap(img_buf_1a_data_fifo_cap),
    .if_empty_n(img_buf_1a_data_empty_n),
    .if_read(addWeighted_0_0_128_128_1_2_2_2_U0_img_buf_1a_data105_read)
);

hls_sobel_axi_stream_top_fifo_w8_d2_S img_buf_1b_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_img_buf_1b_data106_din),
    .if_full_n(img_buf_1b_data_full_n),
    .if_write(Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_img_buf_1b_data106_write),
    .if_dout(img_buf_1b_data_dout),
    .if_num_data_valid(img_buf_1b_data_num_data_valid),
    .if_fifo_cap(img_buf_1b_data_fifo_cap),
    .if_empty_n(img_buf_1b_data_empty_n),
    .if_read(addWeighted_0_0_128_128_1_2_2_2_U0_img_buf_1b_data106_read)
);

hls_sobel_axi_stream_top_fifo_w8_d2_S img_buf_2_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(addWeighted_0_0_128_128_1_2_2_2_U0_img_buf_2_data107_din),
    .if_full_n(img_buf_2_data_full_n),
    .if_write(addWeighted_0_0_128_128_1_2_2_2_U0_img_buf_2_data107_write),
    .if_dout(img_buf_2_data_dout),
    .if_num_data_valid(img_buf_2_data_num_data_valid),
    .if_fifo_cap(img_buf_2_data_fifo_cap),
    .if_empty_n(img_buf_2_data_empty_n),
    .if_read(gray2bgr_0_9_128_128_1_2_2_U0_img_buf_2_data107_read)
);

hls_sobel_axi_stream_top_fifo_w24_d2_S img_buf_3_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(gray2bgr_0_9_128_128_1_2_2_U0_img_buf_3_data108_din),
    .if_full_n(img_buf_3_data_full_n),
    .if_write(gray2bgr_0_9_128_128_1_2_2_U0_img_buf_3_data108_write),
    .if_dout(img_buf_3_data_dout),
    .if_num_data_valid(img_buf_3_data_num_data_valid),
    .if_fifo_cap(img_buf_3_data_fifo_cap),
    .if_empty_n(img_buf_3_data_empty_n),
    .if_read(xfMat2AXIvideo_32_9_128_128_1_2_U0_img_buf_3_data108_read)
);

hls_sobel_axi_stream_top_start_for_bgr2gray_9_0_128_128_1_2_2_U0 start_for_bgr2gray_9_0_128_128_1_2_2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_bgr2gray_9_0_128_128_1_2_2_U0_din),
    .if_full_n(start_for_bgr2gray_9_0_128_128_1_2_2_U0_full_n),
    .if_write(AXIvideo2xfMat_32_9_128_128_1_2_U0_start_write),
    .if_dout(start_for_bgr2gray_9_0_128_128_1_2_2_U0_dout),
    .if_empty_n(start_for_bgr2gray_9_0_128_128_1_2_2_U0_empty_n),
    .if_read(bgr2gray_9_0_128_128_1_2_2_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_img_buf_0_cols_c16_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_img_buf_0_cols_c16_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_img_buf_0_cols_c16_channel <= ap_sync_channel_write_img_buf_0_cols_c16_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_img_buf_0_rows_c15_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_img_buf_0_rows_c15_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_img_buf_0_rows_c15_channel <= ap_sync_channel_write_img_buf_0_rows_c15_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_img_buf_1_cols_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_img_buf_1_cols_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_img_buf_1_cols_channel <= ap_sync_channel_write_img_buf_1_cols_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_img_buf_1_rows_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_img_buf_1_rows_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_img_buf_1_rows_channel <= ap_sync_channel_write_img_buf_1_rows_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_img_buf_1a_cols_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_img_buf_1a_cols_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_img_buf_1a_cols_channel <= ap_sync_channel_write_img_buf_1a_cols_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_img_buf_1a_rows_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_img_buf_1a_rows_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_img_buf_1a_rows_channel <= ap_sync_channel_write_img_buf_1a_rows_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_img_buf_2_cols_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_img_buf_2_cols_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_img_buf_2_cols_channel <= ap_sync_channel_write_img_buf_2_cols_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_img_buf_2_rows_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_img_buf_2_rows_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_img_buf_2_rows_channel <= ap_sync_channel_write_img_buf_2_rows_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_img_buf_3_cols_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_img_buf_3_cols_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_img_buf_3_cols_channel <= ap_sync_channel_write_img_buf_3_cols_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_img_buf_3_rows_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_img_buf_3_rows_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_img_buf_3_rows_channel <= ap_sync_channel_write_img_buf_3_rows_channel;
        end
    end
end

assign AXIvideo2xfMat_32_9_128_128_1_2_U0_ap_continue = 1'b1;

assign AXIvideo2xfMat_32_9_128_128_1_2_U0_ap_start = (img_buf_0_rows_c15_channel_empty_n & img_buf_0_cols_c16_channel_empty_n);

assign Block_entry1_proc_U0_ap_continue = (ap_sync_channel_write_img_buf_3_rows_channel & ap_sync_channel_write_img_buf_3_cols_channel & ap_sync_channel_write_img_buf_2_rows_channel & ap_sync_channel_write_img_buf_2_cols_channel & ap_sync_channel_write_img_buf_1a_rows_channel & ap_sync_channel_write_img_buf_1a_cols_channel & ap_sync_channel_write_img_buf_1_rows_channel & ap_sync_channel_write_img_buf_1_cols_channel & ap_sync_channel_write_img_buf_0_rows_c15_channel & ap_sync_channel_write_img_buf_0_cols_c16_channel);

assign Block_entry1_proc_U0_ap_start = ap_start;

assign Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_ap_continue = 1'b1;

assign Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_ap_start = (img_buf_1_rows_channel_empty_n & img_buf_1_cols_channel_empty_n);

assign addWeighted_0_0_128_128_1_2_2_2_U0_ap_continue = 1'b1;

assign addWeighted_0_0_128_128_1_2_2_2_U0_ap_start = (img_buf_1a_rows_channel_empty_n & img_buf_1a_cols_channel_empty_n);

assign ap_channel_done_img_buf_0_cols_c16_channel = ((ap_sync_reg_channel_write_img_buf_0_cols_c16_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_img_buf_0_rows_c15_channel = ((ap_sync_reg_channel_write_img_buf_0_rows_c15_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_img_buf_1_cols_channel = ((ap_sync_reg_channel_write_img_buf_1_cols_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_img_buf_1_rows_channel = ((ap_sync_reg_channel_write_img_buf_1_rows_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_img_buf_1a_cols_channel = ((ap_sync_reg_channel_write_img_buf_1a_cols_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_img_buf_1a_rows_channel = ((ap_sync_reg_channel_write_img_buf_1a_rows_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_img_buf_2_cols_channel = ((ap_sync_reg_channel_write_img_buf_2_cols_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_img_buf_2_rows_channel = ((ap_sync_reg_channel_write_img_buf_2_rows_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_img_buf_3_cols_channel = ((ap_sync_reg_channel_write_img_buf_3_cols_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_img_buf_3_rows_channel = ((ap_sync_reg_channel_write_img_buf_3_rows_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_done = xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_done;

assign ap_idle = (xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_idle & gray2bgr_0_9_128_128_1_2_2_U0_ap_idle & (img_buf_0_cols_c16_channel_empty_n ^ 1'b1) & (img_buf_0_rows_c15_channel_empty_n ^ 1'b1) & (img_buf_3_cols_channel_empty_n ^ 1'b1) & (img_buf_3_rows_channel_empty_n ^ 1'b1) & (img_buf_2_cols_channel_empty_n ^ 1'b1) & (img_buf_2_rows_channel_empty_n ^ 1'b1) & (img_buf_1a_cols_channel_empty_n ^ 1'b1) & (img_buf_1a_rows_channel_empty_n ^ 1'b1) & (img_buf_1_cols_channel_empty_n ^ 1'b1) & (img_buf_1_rows_channel_empty_n ^ 1'b1) & bgr2gray_9_0_128_128_1_2_2_U0_ap_idle & addWeighted_0_0_128_128_1_2_2_2_U0_ap_idle & Sobel_0_3_0_0_128_128_1_false_2_2_2_U0_ap_idle & Block_entry1_proc_U0_ap_idle & AXIvideo2xfMat_32_9_128_128_1_2_U0_ap_idle);

assign ap_ready = Block_entry1_proc_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_channel_write_img_buf_0_cols_c16_channel = ((img_buf_0_cols_c16_channel_full_n & ap_channel_done_img_buf_0_cols_c16_channel) | ap_sync_reg_channel_write_img_buf_0_cols_c16_channel);

assign ap_sync_channel_write_img_buf_0_rows_c15_channel = ((img_buf_0_rows_c15_channel_full_n & ap_channel_done_img_buf_0_rows_c15_channel) | ap_sync_reg_channel_write_img_buf_0_rows_c15_channel);

assign ap_sync_channel_write_img_buf_1_cols_channel = ((img_buf_1_cols_channel_full_n & ap_channel_done_img_buf_1_cols_channel) | ap_sync_reg_channel_write_img_buf_1_cols_channel);

assign ap_sync_channel_write_img_buf_1_rows_channel = ((img_buf_1_rows_channel_full_n & ap_channel_done_img_buf_1_rows_channel) | ap_sync_reg_channel_write_img_buf_1_rows_channel);

assign ap_sync_channel_write_img_buf_1a_cols_channel = ((img_buf_1a_cols_channel_full_n & ap_channel_done_img_buf_1a_cols_channel) | ap_sync_reg_channel_write_img_buf_1a_cols_channel);

assign ap_sync_channel_write_img_buf_1a_rows_channel = ((img_buf_1a_rows_channel_full_n & ap_channel_done_img_buf_1a_rows_channel) | ap_sync_reg_channel_write_img_buf_1a_rows_channel);

assign ap_sync_channel_write_img_buf_2_cols_channel = ((img_buf_2_cols_channel_full_n & ap_channel_done_img_buf_2_cols_channel) | ap_sync_reg_channel_write_img_buf_2_cols_channel);

assign ap_sync_channel_write_img_buf_2_rows_channel = ((img_buf_2_rows_channel_full_n & ap_channel_done_img_buf_2_rows_channel) | ap_sync_reg_channel_write_img_buf_2_rows_channel);

assign ap_sync_channel_write_img_buf_3_cols_channel = ((img_buf_3_cols_channel_full_n & ap_channel_done_img_buf_3_cols_channel) | ap_sync_reg_channel_write_img_buf_3_cols_channel);

assign ap_sync_channel_write_img_buf_3_rows_channel = ((img_buf_3_rows_channel_full_n & ap_channel_done_img_buf_3_rows_channel) | ap_sync_reg_channel_write_img_buf_3_rows_channel);

assign bgr2gray_9_0_128_128_1_2_2_U0_ap_continue = 1'b1;

assign bgr2gray_9_0_128_128_1_2_2_U0_ap_start = start_for_bgr2gray_9_0_128_128_1_2_2_U0_empty_n;

assign gray2bgr_0_9_128_128_1_2_2_U0_ap_continue = 1'b1;

assign gray2bgr_0_9_128_128_1_2_2_U0_ap_start = (img_buf_2_rows_channel_empty_n & img_buf_2_cols_channel_empty_n);

assign p_dst_TDATA = xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TDATA;

assign p_dst_TDEST = xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TDEST;

assign p_dst_TID = xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TID;

assign p_dst_TKEEP = xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TKEEP;

assign p_dst_TLAST = xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TLAST;

assign p_dst_TSTRB = xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TSTRB;

assign p_dst_TUSER = xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TUSER;

assign p_dst_TVALID = xfMat2AXIvideo_32_9_128_128_1_2_U0_p_dst_TVALID;

assign p_src_TREADY = AXIvideo2xfMat_32_9_128_128_1_2_U0_p_src_TREADY;

assign start_for_bgr2gray_9_0_128_128_1_2_2_U0_din = 1'b1;

assign xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_continue = 1'b1;

assign xfMat2AXIvideo_32_9_128_128_1_2_U0_ap_start = (img_buf_3_rows_channel_empty_n & img_buf_3_cols_channel_empty_n);


reg find_df_deadlock = 0;
// synthesis translate_off
`include "hls_sobel_axi_stream_top_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "hls_sobel_axi_stream_top_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //hls_sobel_axi_stream_top

