// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_sobel_axi_stream_top_AddWeightedKernel_Pipeline_ColLoop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_buf_1a_data105_dout,
        img_buf_1a_data105_num_data_valid,
        img_buf_1a_data105_fifo_cap,
        img_buf_1a_data105_empty_n,
        img_buf_1a_data105_read,
        img_buf_1b_data106_dout,
        img_buf_1b_data106_num_data_valid,
        img_buf_1b_data106_fifo_cap,
        img_buf_1b_data106_empty_n,
        img_buf_1b_data106_read,
        img_buf_2_data107_din,
        img_buf_2_data107_num_data_valid,
        img_buf_2_data107_fifo_cap,
        img_buf_2_data107_full_n,
        img_buf_2_data107_write,
        width
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] img_buf_1a_data105_dout;
input  [1:0] img_buf_1a_data105_num_data_valid;
input  [1:0] img_buf_1a_data105_fifo_cap;
input   img_buf_1a_data105_empty_n;
output   img_buf_1a_data105_read;
input  [7:0] img_buf_1b_data106_dout;
input  [1:0] img_buf_1b_data106_num_data_valid;
input  [1:0] img_buf_1b_data106_fifo_cap;
input   img_buf_1b_data106_empty_n;
output   img_buf_1b_data106_read;
output  [7:0] img_buf_2_data107_din;
input  [1:0] img_buf_2_data107_num_data_valid;
input  [1:0] img_buf_2_data107_fifo_cap;
input   img_buf_2_data107_full_n;
output   img_buf_2_data107_write;
input  [15:0] width;

reg ap_idle;
reg img_buf_1a_data105_read;
reg img_buf_1b_data106_read;
reg img_buf_2_data107_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln71_fu_81_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    img_buf_1a_data105_blk_n;
wire    ap_block_pp0_stage0;
reg    img_buf_1b_data106_blk_n;
reg    img_buf_2_data107_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] pxl_pack_out_V_fu_126_p2;
reg   [7:0] pxl_pack_out_V_reg_143;
reg   [15:0] j_V_fu_44;
wire   [15:0] add_ln1027_fu_87_p2;
wire    ap_loop_init;
reg   [15:0] ap_sig_allocacmp_j_V_load;
reg    ap_block_pp0_stage0_01001;
wire   [6:0] tmp_fu_98_p4;
wire   [6:0] tmp_1_fu_108_p4;
wire   [7:0] zext_ln1495_1_fu_122_p1;
wire   [7:0] zext_ln1495_fu_118_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

hls_sobel_axi_stream_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln71_fu_81_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_V_fu_44 <= add_ln1027_fu_87_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_V_fu_44 <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        pxl_pack_out_V_reg_143 <= pxl_pack_out_V_fu_126_p2;
    end
end

always @ (*) begin
    if (((icmp_ln71_fu_81_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_V_load = 16'd0;
    end else begin
        ap_sig_allocacmp_j_V_load = j_V_fu_44;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_buf_1a_data105_blk_n = img_buf_1a_data105_empty_n;
    end else begin
        img_buf_1a_data105_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_buf_1a_data105_read = 1'b1;
    end else begin
        img_buf_1a_data105_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_buf_1b_data106_blk_n = img_buf_1b_data106_empty_n;
    end else begin
        img_buf_1b_data106_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_buf_1b_data106_read = 1'b1;
    end else begin
        img_buf_1b_data106_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        img_buf_2_data107_blk_n = img_buf_2_data107_full_n;
    end else begin
        img_buf_2_data107_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        img_buf_2_data107_write = 1'b1;
    end else begin
        img_buf_2_data107_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1027_fu_87_p2 = (ap_sig_allocacmp_j_V_load + 16'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((img_buf_2_data107_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((img_buf_1b_data106_empty_n == 1'b0) | (img_buf_1a_data105_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((img_buf_2_data107_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((img_buf_1b_data106_empty_n == 1'b0) | (img_buf_1a_data105_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((img_buf_2_data107_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((img_buf_1b_data106_empty_n == 1'b0) | (img_buf_1a_data105_empty_n == 1'b0))));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((img_buf_1b_data106_empty_n == 1'b0) | (img_buf_1a_data105_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (img_buf_2_data107_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln71_fu_81_p2 = ((ap_sig_allocacmp_j_V_load == width) ? 1'b1 : 1'b0);

assign img_buf_2_data107_din = pxl_pack_out_V_reg_143;

assign pxl_pack_out_V_fu_126_p2 = (zext_ln1495_1_fu_122_p1 + zext_ln1495_fu_118_p1);

assign tmp_1_fu_108_p4 = {{img_buf_1b_data106_dout[7:1]}};

assign tmp_fu_98_p4 = {{img_buf_1a_data105_dout[7:1]}};

assign zext_ln1495_1_fu_122_p1 = tmp_1_fu_108_p4;

assign zext_ln1495_fu_118_p1 = tmp_fu_98_p4;

endmodule //hls_sobel_axi_stream_top_AddWeightedKernel_Pipeline_ColLoop
