// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_sobel_axi_stream_top_Sobel_0_3_0_0_128_128_1_false_2_2_2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        img_buf_1_data104_dout,
        img_buf_1_data104_num_data_valid,
        img_buf_1_data104_fifo_cap,
        img_buf_1_data104_empty_n,
        img_buf_1_data104_read,
        img_buf_1a_data105_din,
        img_buf_1a_data105_num_data_valid,
        img_buf_1a_data105_fifo_cap,
        img_buf_1a_data105_full_n,
        img_buf_1a_data105_write,
        img_buf_1b_data106_din,
        img_buf_1b_data106_num_data_valid,
        img_buf_1b_data106_fifo_cap,
        img_buf_1b_data106_full_n,
        img_buf_1b_data106_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_read;
input  [31:0] p_read1;
input  [7:0] img_buf_1_data104_dout;
input  [1:0] img_buf_1_data104_num_data_valid;
input  [1:0] img_buf_1_data104_fifo_cap;
input   img_buf_1_data104_empty_n;
output   img_buf_1_data104_read;
output  [7:0] img_buf_1a_data105_din;
input  [1:0] img_buf_1a_data105_num_data_valid;
input  [1:0] img_buf_1a_data105_fifo_cap;
input   img_buf_1a_data105_full_n;
output   img_buf_1a_data105_write;
output  [7:0] img_buf_1b_data106_din;
input  [1:0] img_buf_1b_data106_num_data_valid;
input  [1:0] img_buf_1b_data106_fifo_cap;
input   img_buf_1b_data106_full_n;
output   img_buf_1b_data106_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_buf_1_data104_read;
reg img_buf_1a_data105_write;
reg img_buf_1b_data106_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [15:0] width_fu_48_p1;
reg   [15:0] width_reg_58;
wire   [15:0] height_fu_53_p1;
reg   [15:0] height_reg_63;
wire    grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_start;
wire    grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_done;
wire    grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_idle;
wire    grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_ready;
wire    grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_img_buf_1_data104_read;
wire   [7:0] grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_img_buf_1a_data105_din;
wire    grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_img_buf_1a_data105_write;
wire   [7:0] grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_img_buf_1b_data106_din;
wire    grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_img_buf_1b_data106_write;
reg    grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_start_reg;
reg    ap_block_state1_ignore_call7;
wire    ap_CS_fsm_state2;
reg    ap_block_state1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_start_reg = 1'b0;
end

hls_sobel_axi_stream_top_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_start),
    .ap_done(grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_done),
    .ap_idle(grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_idle),
    .ap_ready(grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_ready),
    .img_buf_1_data104_dout(img_buf_1_data104_dout),
    .img_buf_1_data104_num_data_valid(2'd0),
    .img_buf_1_data104_fifo_cap(2'd0),
    .img_buf_1_data104_empty_n(img_buf_1_data104_empty_n),
    .img_buf_1_data104_read(grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_img_buf_1_data104_read),
    .img_buf_1a_data105_din(grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_img_buf_1a_data105_din),
    .img_buf_1a_data105_num_data_valid(2'd0),
    .img_buf_1a_data105_fifo_cap(2'd0),
    .img_buf_1a_data105_full_n(img_buf_1a_data105_full_n),
    .img_buf_1a_data105_write(grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_img_buf_1a_data105_write),
    .img_buf_1b_data106_din(grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_img_buf_1b_data106_din),
    .img_buf_1b_data106_num_data_valid(2'd0),
    .img_buf_1b_data106_fifo_cap(2'd0),
    .img_buf_1b_data106_full_n(img_buf_1b_data106_full_n),
    .img_buf_1b_data106_write(grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_img_buf_1b_data106_write),
    .img_height(height_reg_63),
    .img_width(width_reg_58)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_start_reg <= 1'b1;
        end else if ((grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_ready == 1'b1)) begin
            grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        height_reg_63 <= height_fu_53_p1;
        width_reg_58 <= width_fu_48_p1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        img_buf_1_data104_read = grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_img_buf_1_data104_read;
    end else begin
        img_buf_1_data104_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        img_buf_1a_data105_write = grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_img_buf_1a_data105_write;
    end else begin
        img_buf_1a_data105_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        img_buf_1b_data106_write = grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_img_buf_1b_data106_write;
    end else begin
        img_buf_1b_data106_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call7 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_start = grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_ap_start_reg;

assign height_fu_53_p1 = p_read[15:0];

assign img_buf_1a_data105_din = grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_img_buf_1a_data105_din;

assign img_buf_1b_data106_din = grp_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_fu_36_img_buf_1b_data106_din;

assign width_fu_48_p1 = p_read1[15:0];

endmodule //hls_sobel_axi_stream_top_Sobel_0_3_0_0_128_128_1_false_2_2_2_s
