// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_sobel_axi_stream_top_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_buf_1_data104_dout,
        img_buf_1_data104_num_data_valid,
        img_buf_1_data104_fifo_cap,
        img_buf_1_data104_empty_n,
        img_buf_1_data104_read,
        img_buf_1a_data105_din,
        img_buf_1a_data105_num_data_valid,
        img_buf_1a_data105_fifo_cap,
        img_buf_1a_data105_full_n,
        img_buf_1a_data105_write,
        img_buf_1b_data106_din,
        img_buf_1b_data106_num_data_valid,
        img_buf_1b_data106_fifo_cap,
        img_buf_1b_data106_full_n,
        img_buf_1b_data106_write,
        img_height,
        img_width
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] img_buf_1_data104_dout;
input  [1:0] img_buf_1_data104_num_data_valid;
input  [1:0] img_buf_1_data104_fifo_cap;
input   img_buf_1_data104_empty_n;
output   img_buf_1_data104_read;
output  [7:0] img_buf_1a_data105_din;
input  [1:0] img_buf_1a_data105_num_data_valid;
input  [1:0] img_buf_1a_data105_fifo_cap;
input   img_buf_1a_data105_full_n;
output   img_buf_1a_data105_write;
output  [7:0] img_buf_1b_data106_din;
input  [1:0] img_buf_1b_data106_num_data_valid;
input  [1:0] img_buf_1b_data106_fifo_cap;
input   img_buf_1b_data106_full_n;
output   img_buf_1b_data106_write;
input  [15:0] img_height;
input  [15:0] img_width;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_buf_1_data104_read;
reg[7:0] img_buf_1a_data105_din;
reg img_buf_1a_data105_write;
reg[7:0] img_buf_1b_data106_din;
reg img_buf_1b_data106_write;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    img_buf_1a_data105_blk_n;
wire    ap_CS_fsm_state9;
reg    img_buf_1b_data106_blk_n;
wire   [1:0] bottom_V_fu_276_p3;
reg   [1:0] bottom_V_reg_508;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln1027_fu_223_p2;
wire   [1:0] mid_V_fu_307_p3;
reg   [1:0] mid_V_reg_513;
wire   [1:0] tp_V_fu_338_p3;
reg   [1:0] tp_V_reg_518;
wire   [0:0] cmp_i_i603_i_fu_347_p2;
reg   [0:0] cmp_i_i603_i_reg_523;
wire   [1:0] empty_47_fu_353_p1;
reg   [1:0] empty_47_reg_528;
wire   [7:0] grp_xFGradientX3x3_0_0_s_fu_181_ap_return;
reg   [7:0] ref_tmp_reg_533;
wire    ap_CS_fsm_state8;
wire   [7:0] grp_xFGradientY3x3_0_0_s_fu_194_ap_return;
reg   [7:0] ref_tmp1_reg_538;
reg    buf_V_ce0;
wire   [7:0] buf_V_q0;
reg   [6:0] buf_V_address1;
reg    buf_V_ce1;
reg    buf_V_we1;
reg   [7:0] buf_V_d1;
reg    buf_V_1_ce0;
wire   [7:0] buf_V_1_q0;
reg   [6:0] buf_V_1_address1;
reg    buf_V_1_ce1;
reg    buf_V_1_we1;
reg   [7:0] buf_V_1_d1;
wire   [7:0] buf_V_2_q0;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_done;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_idle;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_ready;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_img_buf_1_data104_read;
wire   [6:0] grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_address1;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_ce1;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_we1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_d1;
wire   [6:0] grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_address1;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_ce1;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_we1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_d1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_done;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_idle;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_ready;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1_data104_read;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1a_data105_din;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1a_data105_write;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1b_data106_din;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1b_data106_write;
wire   [6:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_address0;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_ce0;
wire   [6:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_address1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_ce1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_we1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_d1;
wire   [6:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_address0;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_ce0;
wire   [6:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_address1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_ce1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_we1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_d1;
wire   [6:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_address0;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_ce0;
wire   [6:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_address1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_ce1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_we1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_d1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf3_V_1_out;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf3_V_1_out_ap_vld;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_2_out;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_2_out_ap_vld;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_1_out;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_1_out_ap_vld;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf1_V_1_out;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf1_V_1_out_ap_vld;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_out;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_out_ap_vld;
reg    grp_xFGradientX3x3_0_0_s_fu_181_ap_ce;
wire    ap_CS_fsm_state7;
reg    grp_xFGradientY3x3_0_0_s_fu_194_ap_ce;
reg    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start_reg;
wire    ap_CS_fsm_state6;
reg   [12:0] row_ind_V_fu_70;
wire   [12:0] row_ind_V_2_fu_370_p3;
reg   [12:0] row_V_fu_74;
wire   [12:0] row_V_3_fu_378_p2;
reg   [1:0] tp_fu_78;
reg   [1:0] mid_fu_82;
reg   [1:0] bottom_fu_86;
reg    ap_block_state9;
wire   [15:0] zext_ln1027_fu_219_p1;
wire   [0:0] icmp_ln370_fu_240_p2;
wire   [0:0] icmp_ln370_2_fu_260_p2;
wire   [0:0] icmp_ln370_1_fu_254_p2;
wire   [0:0] empty_42_fu_270_p2;
wire   [1:0] empty_41_fu_266_p1;
wire   [1:0] select_ln370_fu_246_p3;
wire   [0:0] empty_44_fu_301_p2;
wire   [1:0] empty_43_fu_293_p3;
wire   [1:0] select_ln370_1_fu_285_p3;
wire   [0:0] empty_46_fu_332_p2;
wire   [1:0] empty_45_fu_324_p3;
wire   [1:0] select_ln370_2_fu_316_p3;
wire   [12:0] row_ind_V_1_fu_358_p2;
wire   [0:0] icmp_ln1019_fu_364_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start_reg = 1'b0;
#0 grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start_reg = 1'b0;
end

hls_sobel_axi_stream_top_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_buf_V_RAM_S2P_BRAMbkb #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
buf_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_address0),
    .ce0(buf_V_ce0),
    .q0(buf_V_q0),
    .address1(buf_V_address1),
    .ce1(buf_V_ce1),
    .we1(buf_V_we1),
    .d1(buf_V_d1)
);

hls_sobel_axi_stream_top_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_buf_V_RAM_S2P_BRAMbkb #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
buf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_address0),
    .ce0(buf_V_1_ce0),
    .q0(buf_V_1_q0),
    .address1(buf_V_1_address1),
    .ce1(buf_V_1_ce1),
    .we1(buf_V_1_we1),
    .d1(buf_V_1_d1)
);

hls_sobel_axi_stream_top_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_buf_V_RAM_S2P_BRAMbkb #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
buf_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_address0),
    .ce0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_ce0),
    .q0(buf_V_2_q0),
    .address1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_address1),
    .ce1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_ce1),
    .we1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_we1),
    .d1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_d1)
);

hls_sobel_axi_stream_top_xFSobelFilter3x3_Pipeline_Clear_Row_Loop grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start),
    .ap_done(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_done),
    .ap_idle(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_idle),
    .ap_ready(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_ready),
    .img_buf_1_data104_dout(img_buf_1_data104_dout),
    .img_buf_1_data104_num_data_valid(2'd0),
    .img_buf_1_data104_fifo_cap(2'd0),
    .img_buf_1_data104_empty_n(img_buf_1_data104_empty_n),
    .img_buf_1_data104_read(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_img_buf_1_data104_read),
    .img_width(img_width),
    .buf_V_1_address1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_address1),
    .buf_V_1_ce1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_ce1),
    .buf_V_1_we1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_we1),
    .buf_V_1_d1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_d1),
    .buf_V_address1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_address1),
    .buf_V_ce1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_ce1),
    .buf_V_we1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_we1),
    .buf_V_d1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_d1)
);

hls_sobel_axi_stream_top_xFSobelFilter3x3_Pipeline_Col_Loop grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start),
    .ap_done(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_done),
    .ap_idle(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_idle),
    .ap_ready(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_ready),
    .img_buf_1_data104_dout(img_buf_1_data104_dout),
    .img_buf_1_data104_num_data_valid(2'd0),
    .img_buf_1_data104_fifo_cap(2'd0),
    .img_buf_1_data104_empty_n(img_buf_1_data104_empty_n),
    .img_buf_1_data104_read(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1_data104_read),
    .img_buf_1a_data105_din(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1a_data105_din),
    .img_buf_1a_data105_num_data_valid(2'd0),
    .img_buf_1a_data105_fifo_cap(2'd0),
    .img_buf_1a_data105_full_n(img_buf_1a_data105_full_n),
    .img_buf_1a_data105_write(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1a_data105_write),
    .img_buf_1b_data106_din(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1b_data106_din),
    .img_buf_1b_data106_num_data_valid(2'd0),
    .img_buf_1b_data106_fifo_cap(2'd0),
    .img_buf_1b_data106_full_n(img_buf_1b_data106_full_n),
    .img_buf_1b_data106_write(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1b_data106_write),
    .img_width(img_width),
    .tp_V(tp_V_reg_518),
    .mid_V(mid_V_reg_513),
    .bottom_V(bottom_V_reg_508),
    .row_ind_V_cast(empty_47_reg_528),
    .buf_V_2_address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_address0),
    .buf_V_2_ce0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_ce0),
    .buf_V_2_q0(buf_V_2_q0),
    .buf_V_2_address1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_address1),
    .buf_V_2_ce1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_ce1),
    .buf_V_2_we1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_we1),
    .buf_V_2_d1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_d1),
    .buf_V_1_address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_address0),
    .buf_V_1_ce0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_ce0),
    .buf_V_1_q0(buf_V_1_q0),
    .buf_V_1_address1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_address1),
    .buf_V_1_ce1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_ce1),
    .buf_V_1_we1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_we1),
    .buf_V_1_d1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_d1),
    .buf_V_address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_address0),
    .buf_V_ce0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_ce0),
    .buf_V_q0(buf_V_q0),
    .buf_V_address1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_address1),
    .buf_V_ce1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_ce1),
    .buf_V_we1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_we1),
    .buf_V_d1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_d1),
    .cmp_i_i603_i(cmp_i_i603_i_reg_523),
    .src_buf3_V_1_out(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf3_V_1_out),
    .src_buf3_V_1_out_ap_vld(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf3_V_1_out_ap_vld),
    .p_Val2_2_out(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_2_out),
    .p_Val2_2_out_ap_vld(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_2_out_ap_vld),
    .p_Val2_1_out(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_1_out),
    .p_Val2_1_out_ap_vld(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_1_out_ap_vld),
    .src_buf1_V_1_out(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf1_V_1_out),
    .src_buf1_V_1_out_ap_vld(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf1_V_1_out_ap_vld),
    .p_Val2_out(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_out),
    .p_Val2_out_ap_vld(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_out_ap_vld)
);

hls_sobel_axi_stream_top_xFGradientX3x3_0_0_s grp_xFGradientX3x3_0_0_s_fu_181(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .t0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_out),
    .t2(8'd0),
    .m0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_1_out),
    .m2(8'd0),
    .b0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_2_out),
    .b2(8'd0),
    .ap_return(grp_xFGradientX3x3_0_0_s_fu_181_ap_return),
    .ap_ce(grp_xFGradientX3x3_0_0_s_fu_181_ap_ce)
);

hls_sobel_axi_stream_top_xFGradientY3x3_0_0_s grp_xFGradientY3x3_0_0_s_fu_194(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .t0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_out),
    .t1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf1_V_1_out),
    .t2(8'd0),
    .b0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_2_out),
    .b1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf3_V_1_out),
    .b2(8'd0),
    .ap_return(grp_xFGradientY3x3_0_0_s_fu_194_ap_return),
    .ap_ce(grp_xFGradientY3x3_0_0_s_fu_194_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start_reg <= 1'b1;
        end else if ((grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_ready == 1'b1)) begin
            grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1027_fu_223_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start_reg <= 1'b1;
        end else if ((grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_ready == 1'b1)) begin
            grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_V_fu_74 <= 13'd1;
    end else if (((icmp_ln1027_fu_223_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        row_V_fu_74 <= row_V_3_fu_378_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_ind_V_fu_70 <= 13'd2;
    end else if (((icmp_ln1027_fu_223_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        row_ind_V_fu_70 <= row_ind_V_2_fu_370_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_fu_223_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        bottom_V_reg_508 <= bottom_V_fu_276_p3;
        bottom_fu_86 <= bottom_V_fu_276_p3;
        cmp_i_i603_i_reg_523 <= cmp_i_i603_i_fu_347_p2;
        empty_47_reg_528 <= empty_47_fu_353_p1;
        mid_V_reg_513 <= mid_V_fu_307_p3;
        mid_fu_82 <= mid_V_fu_307_p3;
        tp_V_reg_518 <= tp_V_fu_338_p3;
        tp_fu_78 <= tp_V_fu_338_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ref_tmp1_reg_538 <= grp_xFGradientY3x3_0_0_s_fu_194_ap_return;
        ref_tmp_reg_533 <= grp_xFGradientX3x3_0_0_s_fu_181_ap_return;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if (((img_buf_1b_data106_full_n == 1'b0) | (img_buf_1a_data105_full_n == 1'b0))) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln1027_fu_223_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1027_fu_223_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_1_address1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_1_address1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_address1;
    end else begin
        buf_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_1_ce0 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_ce0;
    end else begin
        buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_1_ce1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_1_ce1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_ce1;
    end else begin
        buf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_1_d1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_1_d1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_d1;
    end else begin
        buf_V_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_1_we1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_1_we1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_we1;
    end else begin
        buf_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_address1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_address1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_address1;
    end else begin
        buf_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_ce0 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_ce0;
    end else begin
        buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_ce1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_ce1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_ce1;
    end else begin
        buf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_d1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_d1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_d1;
    end else begin
        buf_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_we1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_we1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_we1;
    end else begin
        buf_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        grp_xFGradientX3x3_0_0_s_fu_181_ap_ce = 1'b1;
    end else begin
        grp_xFGradientX3x3_0_0_s_fu_181_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        grp_xFGradientY3x3_0_0_s_fu_194_ap_ce = 1'b1;
    end else begin
        grp_xFGradientY3x3_0_0_s_fu_194_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        img_buf_1_data104_read = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1_data104_read;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        img_buf_1_data104_read = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_img_buf_1_data104_read;
    end else begin
        img_buf_1_data104_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        img_buf_1a_data105_blk_n = img_buf_1a_data105_full_n;
    end else begin
        img_buf_1a_data105_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((img_buf_1b_data106_full_n == 1'b0) | (img_buf_1a_data105_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9))) begin
        img_buf_1a_data105_din = ref_tmp_reg_533;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        img_buf_1a_data105_din = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1a_data105_din;
    end else begin
        img_buf_1a_data105_din = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1a_data105_din;
    end
end

always @ (*) begin
    if ((~((img_buf_1b_data106_full_n == 1'b0) | (img_buf_1a_data105_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9))) begin
        img_buf_1a_data105_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        img_buf_1a_data105_write = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1a_data105_write;
    end else begin
        img_buf_1a_data105_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        img_buf_1b_data106_blk_n = img_buf_1b_data106_full_n;
    end else begin
        img_buf_1b_data106_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((img_buf_1b_data106_full_n == 1'b0) | (img_buf_1a_data105_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9))) begin
        img_buf_1b_data106_din = ref_tmp1_reg_538;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        img_buf_1b_data106_din = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1b_data106_din;
    end else begin
        img_buf_1b_data106_din = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1b_data106_din;
    end
end

always @ (*) begin
    if ((~((img_buf_1b_data106_full_n == 1'b0) | (img_buf_1a_data105_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9))) begin
        img_buf_1b_data106_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        img_buf_1b_data106_write = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_img_buf_1b_data106_write;
    end else begin
        img_buf_1b_data106_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln1027_fu_223_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if ((~((img_buf_1b_data106_full_n == 1'b0) | (img_buf_1a_data105_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state9 = ((img_buf_1b_data106_full_n == 1'b0) | (img_buf_1a_data105_full_n == 1'b0));
end

assign bottom_V_fu_276_p3 = ((empty_42_fu_270_p2[0:0] == 1'b1) ? empty_41_fu_266_p1 : select_ln370_fu_246_p3);

assign cmp_i_i603_i_fu_347_p2 = ((zext_ln1027_fu_219_p1 < img_height) ? 1'b1 : 1'b0);

assign empty_41_fu_266_p1 = icmp_ln370_2_fu_260_p2;

assign empty_42_fu_270_p2 = (icmp_ln370_2_fu_260_p2 | icmp_ln370_1_fu_254_p2);

assign empty_43_fu_293_p3 = ((icmp_ln370_2_fu_260_p2[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign empty_44_fu_301_p2 = (icmp_ln370_2_fu_260_p2 | icmp_ln370_1_fu_254_p2);

assign empty_45_fu_324_p3 = ((icmp_ln370_2_fu_260_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign empty_46_fu_332_p2 = (icmp_ln370_2_fu_260_p2 | icmp_ln370_1_fu_254_p2);

assign empty_47_fu_353_p1 = row_ind_V_fu_70[1:0];

assign grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start_reg;

assign grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start_reg;

assign icmp_ln1019_fu_364_p2 = ((row_ind_V_1_fu_358_p2 == 13'd3) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_223_p2 = ((zext_ln1027_fu_219_p1 > img_height) ? 1'b1 : 1'b0);

assign icmp_ln370_1_fu_254_p2 = ((row_ind_V_fu_70 == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln370_2_fu_260_p2 = ((row_ind_V_fu_70 == 13'd1) ? 1'b1 : 1'b0);

assign icmp_ln370_fu_240_p2 = ((row_ind_V_fu_70 == 13'd2) ? 1'b1 : 1'b0);

assign mid_V_fu_307_p3 = ((empty_44_fu_301_p2[0:0] == 1'b1) ? empty_43_fu_293_p3 : select_ln370_1_fu_285_p3);

assign row_V_3_fu_378_p2 = (row_V_fu_74 + 13'd1);

assign row_ind_V_1_fu_358_p2 = (row_ind_V_fu_70 + 13'd1);

assign row_ind_V_2_fu_370_p3 = ((icmp_ln1019_fu_364_p2[0:0] == 1'b1) ? 13'd0 : row_ind_V_1_fu_358_p2);

assign select_ln370_1_fu_285_p3 = ((icmp_ln370_fu_240_p2[0:0] == 1'b1) ? 2'd1 : mid_fu_82);

assign select_ln370_2_fu_316_p3 = ((icmp_ln370_fu_240_p2[0:0] == 1'b1) ? 2'd0 : tp_fu_78);

assign select_ln370_fu_246_p3 = ((icmp_ln370_fu_240_p2[0:0] == 1'b1) ? 2'd2 : bottom_fu_86);

assign tp_V_fu_338_p3 = ((empty_46_fu_332_p2[0:0] == 1'b1) ? empty_45_fu_324_p3 : select_ln370_2_fu_316_p3);

assign zext_ln1027_fu_219_p1 = row_V_fu_74;

endmodule //hls_sobel_axi_stream_top_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s
