-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_sobel_axi_stream_top_bgr2gray_9_0_128_128_1_2_2_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_src_rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    p_src_rows_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    p_src_rows_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    p_src_rows_empty_n : IN STD_LOGIC;
    p_src_rows_read : OUT STD_LOGIC;
    p_src_cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    p_src_cols_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    p_src_cols_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    p_src_cols_empty_n : IN STD_LOGIC;
    p_src_cols_read : OUT STD_LOGIC;
    img_buf_0_data103_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    img_buf_0_data103_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img_buf_0_data103_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img_buf_0_data103_empty_n : IN STD_LOGIC;
    img_buf_0_data103_read : OUT STD_LOGIC;
    img_buf_1_data104_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_buf_1_data104_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img_buf_1_data104_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img_buf_1_data104_full_n : IN STD_LOGIC;
    img_buf_1_data104_write : OUT STD_LOGIC );
end;


architecture behav of hls_sobel_axi_stream_top_bgr2gray_9_0_128_128_1_2_2_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_src_rows_blk_n : STD_LOGIC;
    signal p_src_cols_blk_n : STD_LOGIC;
    signal height_fu_73_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal height_reg_116 : STD_LOGIC_VECTOR (15 downto 0);
    signal width_fu_77_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal width_reg_121 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_start : STD_LOGIC;
    signal grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_done : STD_LOGIC;
    signal grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_idle : STD_LOGIC;
    signal grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_ready : STD_LOGIC;
    signal grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_img_buf_0_data103_read : STD_LOGIC;
    signal grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_img_buf_1_data104_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_img_buf_1_data104_write : STD_LOGIC;
    signal grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln1027_fu_93_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_V_fu_48 : STD_LOGIC_VECTOR (12 downto 0);
    signal i_V_4_fu_98_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal zext_ln1027_fu_89_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component hls_sobel_axi_stream_top_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_buf_0_data103_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        img_buf_0_data103_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img_buf_0_data103_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img_buf_0_data103_empty_n : IN STD_LOGIC;
        img_buf_0_data103_read : OUT STD_LOGIC;
        img_buf_1_data104_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_buf_1_data104_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img_buf_1_data104_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img_buf_1_data104_full_n : IN STD_LOGIC;
        img_buf_1_data104_write : OUT STD_LOGIC;
        width : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64 : component hls_sobel_axi_stream_top_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_start,
        ap_done => grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_done,
        ap_idle => grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_idle,
        ap_ready => grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_ready,
        img_buf_0_data103_dout => img_buf_0_data103_dout,
        img_buf_0_data103_num_data_valid => ap_const_lv2_0,
        img_buf_0_data103_fifo_cap => ap_const_lv2_0,
        img_buf_0_data103_empty_n => img_buf_0_data103_empty_n,
        img_buf_0_data103_read => grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_img_buf_0_data103_read,
        img_buf_1_data104_din => grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_img_buf_1_data104_din,
        img_buf_1_data104_num_data_valid => ap_const_lv2_0,
        img_buf_1_data104_fifo_cap => ap_const_lv2_0,
        img_buf_1_data104_full_n => img_buf_1_data104_full_n,
        img_buf_1_data104_write => grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_img_buf_1_data104_write,
        width => width_reg_121);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln1027_fu_93_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln1027_fu_93_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_ready = ap_const_logic_1)) then 
                    grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_V_fu_48_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_V_fu_48 <= ap_const_lv13_0;
            elsif (((icmp_ln1027_fu_93_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_V_fu_48 <= i_V_4_fu_98_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                height_reg_116 <= height_fu_73_p1;
                width_reg_121 <= width_fu_77_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, p_src_rows_empty_n, p_src_cols_empty_n, grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_done, ap_CS_fsm_state2, icmp_ln1027_fu_93_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln1027_fu_93_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, p_src_rows_empty_n, p_src_cols_empty_n)
    begin
        if (((ap_start = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_done)
    begin
        if ((grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, p_src_rows_empty_n, p_src_cols_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln1027_fu_93_p2)
    begin
        if (((icmp_ln1027_fu_93_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln1027_fu_93_p2)
    begin
        if (((icmp_ln1027_fu_93_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_start <= grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg;
    height_fu_73_p1 <= p_src_rows_dout(16 - 1 downto 0);
    i_V_4_fu_98_p2 <= std_logic_vector(unsigned(i_V_fu_48) + unsigned(ap_const_lv13_1));
    icmp_ln1027_fu_93_p2 <= "1" when (unsigned(zext_ln1027_fu_89_p1) < unsigned(height_reg_116)) else "0";

    img_buf_0_data103_read_assign_proc : process(grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_img_buf_0_data103_read, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            img_buf_0_data103_read <= grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_img_buf_0_data103_read;
        else 
            img_buf_0_data103_read <= ap_const_logic_0;
        end if; 
    end process;

    img_buf_1_data104_din <= grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_img_buf_1_data104_din;

    img_buf_1_data104_write_assign_proc : process(grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_img_buf_1_data104_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            img_buf_1_data104_write <= grp_bgr2gray_9_0_128_128_1_2_2_Pipeline_columnloop_fu_64_img_buf_1_data104_write;
        else 
            img_buf_1_data104_write <= ap_const_logic_0;
        end if; 
    end process;


    p_src_cols_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src_cols_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_cols_blk_n <= p_src_cols_empty_n;
        else 
            p_src_cols_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_cols_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src_rows_empty_n, p_src_cols_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_cols_read <= ap_const_logic_1;
        else 
            p_src_cols_read <= ap_const_logic_0;
        end if; 
    end process;


    p_src_rows_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src_rows_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_rows_blk_n <= p_src_rows_empty_n;
        else 
            p_src_rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_rows_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src_rows_empty_n, p_src_cols_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_rows_read <= ap_const_logic_1;
        else 
            p_src_rows_read <= ap_const_logic_0;
        end if; 
    end process;

    width_fu_77_p1 <= p_src_cols_dout(16 - 1 downto 0);
    zext_ln1027_fu_89_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_V_fu_48),16));
end behav;
